package com.example.financialliteracyapp.ui.navigation

object Routes {
    const val ONBOARDING = "onboarding"
    const val MAIN = "main"
    const val PET = "pet"
    const val BANKS = "banks"
    const val SHOP = "shop"
    const val KIOSK = "kiosk"
    const val HIRE = "hire"
    const val MARKET = "market"
    const val MAP = "map"
    const val GOALS = "goals"
    const val INVENTORY = "inventory"
    const val PNL = "pnl"
    const val SUPPLIERS = "minigame_suppliers"
    const val PRICER = "minigame_pricer"
    const val SHELVES = "minigame_shelves"
    const val CASHIER = "minigame_cashier"
    const val CLEANING = "minigame_cleaning"
    const val REPORT = "report"
    const val LOT = "lot"
    const val JOURNAL = "journal"
    const val QUESTS = "quests"
    const val PROGRESS = "progress"
    const val REFERENCE = "reference"
    const val ADULT = "adult"
    const val ENTERTAINMENT = "entertainment"
    const val BUILDING = "building"
    const val CONSTRUCTION = "construction"
    const val AUTO_SERVICE = "auto_service"
    const val APPEARANCE = "appearance"
    const val CHEATS = "cheats"
}